"use strict";

const SALIMA_PRODUCTS = [
  {id:"set-elkol-rice",category:"food",brand:"set-elkol",image:"assets/products/real/set-elkol-rice.png",featured:true,weight:"5 كغم",ar:{name:"أرز ست الكل بسمتي",short:"أرز بسمتي فاخر طويل الحبة بعبوة 5 كغم.",description:"أرز ست الكل البسمتي طويل الحبة، مناسب للأطباق التي تحتاج حبّة مفلفلة وشكلًا أنيقًا بعد الطهي.",use:"الكبسة، المندي، البرياني والأطباق الرئيسية.",storage:"يُحفظ في مكان جاف وبارد بعيدًا عن الرطوبة.",packaging:"عبوة محكمة الإغلاق - 5 كغم."},en:{name:"Set El Kol Premium Basmati Rice",short:"Premium extra-long basmati rice in a 5 kg pack.",description:"Set El Kol premium extra-long basmati rice, ideal for dishes that need separate, elegant grains.",use:"Kabsa, mandi, biryani and main dishes.",storage:"Store in a cool, dry place away from moisture.",packaging:"Resealable 5 kg pack."}},
  {id:"sunbird-rice",category:"food",brand:"sunbird",image:"assets/products/real/sunbird-rice.png",featured:true,weight:"5 كغم",ar:{name:"أرز SunBird ياسمين",short:"أرز ياسمين تايلندي عطري للاستخدام اليومي.",description:"أرز ياسمين عطري من تايلاند بحبة ناعمة ورائحة مميزة، مناسب للأطباق الآسيوية واليومية.",use:"الأطباق الآسيوية، الأرز الأبيض والوجبات المنزلية.",storage:"يُحفظ في مكان جاف وبارد.",packaging:"كيس أرز ياسمين 5 كغم."},en:{name:"SunBird Jasmine Rice",short:"Fragrant Thai jasmine rice for everyday cooking.",description:"Thai fragrant jasmine rice with a soft grain and distinctive aroma.",use:"Asian dishes, steamed rice and daily meals.",storage:"Store in a cool, dry place.",packaging:"5 kg jasmine rice sack."}},
  {id:"aeroplane-rice",category:"food",brand:"aeroplane",image:"assets/products/real/aeroplane-rice.png",featured:false,weight:"7 كغم",ar:{name:"أرز Aeroplane بسمتي",short:"أرز بسمتي هندي طويل الحبة بعبوة 7 كغم.",description:"أرز بسمتي هندي طويل الحبة بعبوة عملية ذات مقبض، مناسب للعائلات والاستخدام المتكرر.",use:"البرياني، الكبسة والأرز المفلفل.",storage:"يُحفظ بعيدًا عن الرطوبة والحرارة.",packaging:"كيس بمقبض - 7 كغم."},en:{name:"Aeroplane Basmati Rice",short:"Extra-long Indian basmati rice in a 7 kg pack.",description:"Long-grain Indian basmati rice in a practical handled pack.",use:"Biryani, kabsa and fluffy rice dishes.",storage:"Keep away from moisture and heat.",packaging:"Handled 7 kg bag."}},
  {id:"atlantic-rice",category:"food",brand:"atlantic",image:"assets/products/real/atlantic-rice.png",featured:false,weight:"5 كغم",ar:{name:"أرز Atlantic كامولينو",short:"أرز أبيض كامولينو بعبوة 5 كغم.",description:"أرز كامولينو أبيض بحبة متوسطة، مناسب للطبخ اليومي والوصفات المنزلية المتنوعة.",use:"المحاشي، الأرز اليومي والأطباق الجانبية.",storage:"يُحفظ في مكان جاف وبارد.",packaging:"عبوة شفافة جزئيًا - 5 كغم."},en:{name:"Atlantic Camolino White Rice",short:"Camolino white rice in a 5 kg pack.",description:"Medium-grain camolino white rice for everyday cooking and varied recipes.",use:"Stuffed vegetables, daily rice and side dishes.",storage:"Store in a cool, dry place.",packaging:"Partially transparent 5 kg pack."}},
  {id:"set-elkol-tissues",category:"home",brand:"set-elkol",image:"assets/products/real/set-elkol-tissues.png",featured:true,weight:"",ar:{name:"محارم ست الكل",short:"محارم ناعمة بتصميم زهري للاستخدام اليومي.",description:"محارم ست الكل بعبوة أنيقة وناعمة مناسبة للمنزل والمكتب.",use:"الاستخدام اليومي في المنزل أو المكتب.",storage:"تُحفظ في مكان نظيف وجاف.",packaging:"عبوة محارم مغلفة."},en:{name:"Set El Kol Tissues",short:"Soft floral-design tissues for everyday use.",description:"Soft Set El Kol tissues in an elegant pack for home and office.",use:"Everyday use at home or work.",storage:"Keep in a clean, dry place.",packaging:"Wrapped tissue pack."}},
  {id:"diana-tissues",category:"home",brand:"diana",image:"assets/products/real/diana-tissues.png",featured:false,weight:"",ar:{name:"محارم ديانا",short:"محارم ناعمة بعبوة زرقاء عملية.",description:"محارم ديانا بعبوة عملية وهوية زرقاء واضحة، مناسبة للاستخدام اليومي.",use:"المنزل، المكتب والأماكن العامة.",storage:"تُحفظ بعيدًا عن الرطوبة.",packaging:"عبوة محارم ديانا."},en:{name:"Diana Tissues",short:"Soft tissues in a practical blue pack.",description:"Diana tissues in a practical, easy-to-recognize blue package.",use:"Home, office and shared spaces.",storage:"Keep away from moisture.",packaging:"Diana tissue pack."}},
  {id:"tuna",category:"canned",brand:"salima",image:"assets/products/real/tuna.png",featured:true,weight:"",ar:{name:"تونة سليمة الخفيفة",short:"قطع تونة خفيفة في زيت دوار الشمس.",description:"تونة سليمة الخفيفة بقطع متماسكة في زيت دوار الشمس، مناسبة للوجبات السريعة.",use:"السلطات، السندويشات والوجبات الخفيفة.",storage:"تُحفظ في مكان بارد وجاف، وبعد الفتح تُبرد.",packaging:"علبة معدنية سهلة التخزين."},en:{name:"Salima Light Tuna Chunks",short:"Light tuna chunks in sunflower oil.",description:"Firm Salima light tuna chunks packed in sunflower oil.",use:"Salads, sandwiches and quick meals.",storage:"Store cool and dry; refrigerate after opening.",packaging:"Compact metal can."}},
  {id:"beans",category:"canned",brand:"salima",image:"assets/products/real/beans.png",featured:true,weight:"",ar:{name:"فول مدمس سليمة",short:"فول مدمس جاهز للأكل بدون مواد حافظة.",description:"فول مدمس سليمة جاهز للتقديم، مناسب للفطور والوجبات السريعة.",use:"الفطور، المقبلات والأطباق الجانبية.",storage:"يُحفظ في مكان جاف وبارد وبعد الفتح يُبرد.",packaging:"علبة معدنية."},en:{name:"Salima Foul Medammas",short:"Ready-to-eat fava beans with no preservatives.",description:"Ready-to-serve Salima fava beans for breakfast and quick meals.",use:"Breakfast, appetizers and side dishes.",storage:"Store cool and dry; refrigerate after opening.",packaging:"Metal can."}},
  {id:"oil",category:"oil",brand:"salima",image:"assets/products/real/oil.png",featured:false,weight:"5 لتر",ar:{name:"زيت دوار الشمس سليمة",short:"زيت دوار الشمس للطهي والقلي بعبوة عائلية.",description:"زيت دوار الشمس سليمة بعبوة كبيرة عملية للاستخدام المنزلي اليومي.",use:"الطهي، القلي وتحضير الوجبات.",storage:"يُحفظ بعيدًا عن الضوء والحرارة.",packaging:"عبوة بلاستيكية 5 لتر."},en:{name:"Salima Sunflower Oil",short:"Family-size sunflower oil for cooking and frying.",description:"Salima sunflower oil in a practical large bottle for daily household use.",use:"Cooking, frying and meal preparation.",storage:"Keep away from light and heat.",packaging:"5 L plastic bottle."}}
];

const SALIMA_BRANDS = [
  {id:"all",ar:"الكل",en:"All"},{id:"salima",ar:"سليمة",en:"Salima"},{id:"set-elkol",ar:"ست الكل",en:"Set El Kol"},{id:"sunbird",ar:"SunBird",en:"SunBird"},{id:"aeroplane",ar:"Aeroplane",en:"Aeroplane"},{id:"atlantic",ar:"Atlantic",en:"Atlantic"},{id:"diana",ar:"Diana",en:"Diana"}
];
