"use strict";
const params=new URLSearchParams(location.search);let language=params.get("lang")==="en"?"en":"ar";let theme=localStorage.getItem("salima-theme")==="dark"?"dark":"light";const selectedProduct=SALIMA_PRODUCTS.find(p=>p.id===params.get("id"));
const tx=(x,k)=>language==="ar"?x[`${k}Ar`]:x[`${k}En`];const cat=id=>SALIMA_CATEGORIES.find(c=>c.id===id);const brand=id=>SALIMA_BRANDS.find(b=>b.id===id);const labels={ar:{back:"← العودة إلى المنتجات",brand:"العلامة",category:"القسم",type:"النوع",weight:"الوزن",quantity:"الكمية",pieces:"عدد القطع",packages:"عدد العبوات",description:"الوصف",share:"مشاركة",copy:"نسخ الرابط",copied:"تم النسخ",related:"منتجات مشابهة",missing:"المنتج غير موجود",missingText:"تعذر العثور على المنتج المطلوب.",details:"عرض التفاصيل"},en:{back:"← Back to products",brand:"Brand",category:"Category",type:"Type",weight:"Weight",quantity:"Quantity",pieces:"Pieces",packages:"Packages",description:"Description",share:"Share",copy:"Copy link",copied:"Copied",related:"Related products",missing:"Product not found",missingText:"The requested product could not be found.",details:"View details"}};
function card(p){return `<article class="product-card"><div class="product-media"><img src="${p.images[0]}" alt="${tx(p,"name")}" loading="lazy"></div><div class="product-body"><span class="product-category">${tx(cat(p.category),"name")}</span><h3>${tx(p,"name")}</h3><a class="product-button" href="product.html?id=${p.id}&lang=${language}">${labels[language].details}</a></div></article>`}
function render(){
  const l=labels[language];document.documentElement.lang=language;document.documentElement.dir=language==="ar"?"rtl":"ltr";document.documentElement.dataset.theme=theme;document.querySelector("#productLanguage").textContent=language==="ar"?"EN":"ع";document.querySelector("#productBack").textContent=l.back;document.querySelector("#productShare").textContent=l.share;document.querySelector("#productCopy").textContent=l.copy;
  if(!selectedProduct){document.querySelector("#productNotFound").hidden=false;document.querySelector("#productNotFound h1").textContent=l.missing;document.querySelector("#productNotFound p").textContent=l.missingText;document.title=`${l.missing} | Salima`;return}
  document.querySelector("#productPageCard").hidden=false;document.querySelector("#productPageImage").src=selectedProduct.images[0];document.querySelector("#productPageImage").alt=tx(selectedProduct,"name");document.querySelector("#productPageCategory").textContent=tx(cat(selectedProduct.category),"name");document.querySelector("#productPageTitle").textContent=tx(selectedProduct,"name");
  const rows=[[l.category,tx(cat(selectedProduct.category),"name")],[l.brand,brand(selectedProduct.brand)?tx(brand(selectedProduct.brand),"name"):""],[l.type,tx(selectedProduct,"type")],[l.weight,tx(selectedProduct,"weight")],[l.quantity,tx(selectedProduct,"quantity")],[l.pieces,selectedProduct.piecesCount],[l.packages,selectedProduct.packageCount],[l.description,tx(selectedProduct,"description")]].filter(([,v])=>v);document.querySelector("#productPageMeta").innerHTML=rows.slice(0,3).map(([,v])=>`<span>${v}</span>`).join("");document.querySelector("#productPageDescription").hidden=!tx(selectedProduct,"description");document.querySelector("#productPageDescription").textContent=tx(selectedProduct,"description");document.querySelector("#productPageDetails").innerHTML=rows.slice(3).map(([k,v])=>`<article><div><h3>${k}</h3><p>${v}</p></div></article>`).join("");
  const related=SALIMA_PRODUCTS.filter(p=>p.category===selectedProduct.category&&p.id!==selectedProduct.id).slice(0,4);document.querySelector("#productPageRelated").hidden=!related.length;document.querySelector("#productRelatedTitle").textContent=l.related;document.querySelector("#productRelatedGrid").innerHTML=related.map(card).join("");document.title=`${tx(selectedProduct,"name")} | Salima`;document.querySelector("meta[name=description]").content=language==="ar"?`تفاصيل ${tx(selectedProduct,"name")} من كتالوج سليمة.`:`${tx(selectedProduct,"name")} details from the Salima catalog.`;
}
async function copy(){await navigator.clipboard.writeText(location.href);const b=document.querySelector("#productCopy");b.textContent=labels[language].copied;setTimeout(()=>b.textContent=labels[language].copy,1400)}async function share(){if(navigator.share)await navigator.share({title:document.title,url:location.href}).catch(()=>{});else await copy()}
document.querySelector("#productLanguage").addEventListener("click",()=>{language=language==="ar"?"en":"ar";render()});document.querySelector("#productTheme").addEventListener("click",()=>{theme=theme==="light"?"dark":"light";localStorage.setItem("salima-theme",theme);render()});document.querySelector("#productCopy").addEventListener("click",copy);document.querySelector("#productShare").addEventListener("click",share);render();
